import mongoose from "mongoose";

const inventorySchema = new mongoose.Schema(
   {
      dealerName: {
         type: String,
         required: [true, "Dealer name is required"],
         trim: true,
      },
      farmerDealerCode: {
         type: String,
         required: [true, "Dealer code is required"],
         trim: true,
      },
      financialYear: {
         type: String,
         required: [true, "Financial year is required"],
         trim: true,
      },
      date: {
         type: Date,
         required: [true, "Date is required"],
      },
      challanNo: {
         type: String,
         required: [true, "Challan number is required"],
         trim: true,
      },
      acre: {
         type: Number,
         default: null,
      },
      products: {
         // 12 MM
         "12MmEndCap": { type: Number, default: 0 },
         "12MmLateralPlain": { type: Number, default: 0 },
         // 16 MM 
         "16MmBallValve": { type: Number, default: 0 },
         "16MmEndCap": { type: Number, default: 0 },
         "16MmGrometNeta": { type: Number, default: 0 },
         "16MmInLineLateral": { type: Number, default: 0 },
         "16MmInLineLateral16x2x30NeerShakti": { type: Number, default: 0 },
         "16MmInLineLateral16x4x60Mungipa": { type: Number, default: 0 },
         "16MmInLineLateral16x4x60NeerShakti": { type: Number, default: 0 },
         "16MmInLineLateral16x4x30NeerShakti": { type: Number, default: 0 },
         "16MmJoiner": { type: Number, default: 0 },
         "16MmLateral16x4x40NeerShakti": { type: Number, default: 0 },
         "16MmLateralClass2IsiPlain": { type: Number, default: 0 },
         "16MmTakeOff": { type: Number, default: 0 },
         "16MmTee": { type: Number, default: 0 },
         "16x12x16MmTee": { type: Number, default: 0 },

         // 32 MM
         "32MmBallValveAds": { type: Number, default: 0 },
         "32MmBallValveAsmiPlain": { type: Number, default: 0 },
         "32MmBallValveMungipa": { type: Number, default: 0 },
         "32MmBallValveNeerShakti": { type: Number, default: 0 },
         "32MmBendPpElbow": { type: Number, default: 0 },
         "32MmEndCap": { type: Number, default: 0 },
         "32MmEndPlug": { type: Number, default: 0 },
         "32MmHexa": { type: Number, default: 0 },
         "32MmJoiner": { type: Number, default: 0 },
         "32MmLateralClass2ForMiniSprinklerMungipa": { type: Number, default: 0 },
         "32MmLateralClIiAOneKissan": { type: Number, default: 0 },
         "32MmLateralClIiForMiniNeerShakti": { type: Number, default: 0 },
         "32MmLateralClIiForMiniSprinklerAds": { type: Number, default: 0 },
         "32MmMtafta": { type: Number, default: 0 },
         "32MmServiceSaddle75x32": { type: Number, default: 0 },
         "32MmTee": { type: Number, default: 0 },

         // 63 MM
         "63MmBallValveMs": { type: Number, default: 0 },
         "63MmHdpe6MtrPipeDulyCoupledMungipa": { type: Number, default: 0 },
         "63MmHdpePipe": { type: Number, default: 0 },
         "63MmHdpePipe6MtrNeerShakti": { type: Number, default: 0 },
         "63MmHdpePipeDulyCoupled6MtrNeerShakti": { type: Number, default: 0 },
         "63MmHdpeSprinklerBend": { type: Number, default: 0 },
         "63MmPvcElbow": { type: Number, default: 0 },
         "63MmPvcFtamta": { type: Number, default: 0 },
         "63MmPvcTee": { type: Number, default: 0 },
         "63MmSandFilter": { type: Number, default: 0 },
         "63MmServiceSaddle63x32": { type: Number, default: 0 },
         "63MmSprinklerEndCapMungipa": { type: Number, default: 0 },
         "63MmSprinklerRubberRing": { type: Number, default: 0 },
         "63MmSprinklerTee": { type: Number, default: 0 },
         "63X4KgPvcPipe": { type: Number, default: 0 },

         // 75 MM
         "75MmAlmPipe3Mtr": { type: Number, default: 0 },
         "75MmAluminiumBend": { type: Number, default: 0 },
         "75MmAluminiumClampPcs": { type: Number, default: 0 },
         "75MmAluminiumEndCap": { type: Number, default: 0 },
         "75MmAluminiumFootBattenPcs": { type: Number, default: 0 },
         "75MmAluminiumPipemlc6Mtr": { type: Number, default: 0 },
         "75MmAluminiumPipeslc6Mtr": { type: Number, default: 0 },
         "75MmBallValveMs": { type: Number, default: 0 },
         "75MmClampEpcGiPcs": { type: Number, default: 0 },
         "75MmHdpePipe": { type: Number, default: 0 },
         "75MmHdpePipe3MtrAds": { type: Number, default: 0 },
         "75MmHdpePipe3MtrMungipa": { type: Number, default: 0 },
         "75MmHdpePipe3MtrNeerShakti": { type: Number, default: 0 },
         "75MmHdpePipe6MtrNeerShakti": { type: Number, default: 0 },
         "75MmHdpePipe6MtrDulyCoupledAds": { type: Number, default: 0 },
         "75MmHdpePipe6MtrDulyCoupledMungipa": { type: Number, default: 0 },
         "75MmHdpePipe6MtrDulyCoupledNeerShakti": { type: Number, default: 0 },
         "75MmHdpeSprinklerPcn": { type: Number, default: 0 },
         "75MmPvcElbow": { type: Number, default: 0 },
         "75MmPvcFtamta": { type: Number, default: 0 },
         "75MmPvcTee": { type: Number, default: 0 },
         "75MmSprinklerAdopterAds": { type: Number, default: 0 },
         "75MmSprinklerAdopterMungipa": { type: Number, default: 0 },
         "75MmSprinklerAdopterNeerShakti": { type: Number, default: 0 },
         "75MmSprinklerBendAds": { type: Number, default: 0 },
         "75MmSprinklerBendMungipa": { type: Number, default: 0 },
         "75MmSprinklerBendNeerShakti": { type: Number, default: 0 },
         "75MmSprinklerBendPlainWithoutClamp": { type: Number, default: 0 },
         "75MmSprinklerEndCapAds": { type: Number, default: 0 },
         "75MmSprinklerEndCapMungipa": { type: Number, default: 0 },
         "75MmSprinklerEndCapNeerShakti": { type: Number, default: 0 },
         "75MmSprinklerPcnAds": { type: Number, default: 0 },
         "75MmSprinklerPcnNeerShakti": { type: Number, default: 0 },
         "75MmSprinklerRubberRing": { type: Number, default: 0 },
         "75MmSprinklerTeeAds": { type: Number, default: 0 },
         "75MmSprinklerTeeMungipa": { type: Number, default: 0 },
         "75MmSprinklerTeeNeerShakti": { type: Number, default: 0 },
         "75X4KgPvcPipe": { type: Number, default: 0 },
         "75x63MmPvcTee": { type: Number, default: 0 },

         // 90 MM
         "90MmHdpePipe": { type: Number, default: 0 },
         "90MmHdpePipe3MtrNeerShakti": { type: Number, default: 0 },
         "90MmHdpePipe6MtrDulyCoupledNeerShakti": { type: Number, default: 0 },
         "90MmHdpeSprinklerPcnNeerShakti": { type: Number, default: 0 },
         "90MmServiceSaddle90x32": { type: Number, default: 0 },
         "90MmSprinklerBend": { type: Number, default: 0 },
         "90MmSprinklerEndCap": { type: Number, default: 0 },
         "90MmSprinklerEndCapNeerShakti": { type: Number, default: 0 },
         "90MmSprinklerRubberRing": { type: Number, default: 0 },
         "90MmSprinklerTee": { type: Number, default: 0 },
         // Misc / Accessories
         "airReleaseValve1": { type: Number, default: 0 },
         "aluminiumRivet": { type: Number, default: 0 },
         "drippers8Lph": { type: Number, default: 0 },
         "fertilizerTank": { type: Number, default: 0 },
         "flashValve63Mm75Mm": { type: Number, default: 0 },
         "giRiserPipe34": { type: Number, default: 0 },
         "hydroCycloneFilterMungipa": { type: Number, default: 0 },
         "hydroCycloneFilterNeerShakti": { type: Number, default: 0 },
         "manifold25": { type: Number, default: 0 },
         "miniSprinklerPlasticNozzleAds": { type: Number, default: 0 },
         "miniSprinklerPlasticNozzleMungipa": { type: Number, default: 0 },
         "miniSprinklerPlasticNozzleNeerShakti": { type: Number, default: 0 },
         "pressureGauze25": { type: Number, default: 0 },
         "pvcReducer75x63": { type: Number, default: 0 },
         "pvcSolvent100Ml": { type: Number, default: 0 },
         "sandFilter": { type: Number, default: 0 },
         "screenFilterNeerShakti": { type: Number, default: 0 },
         "sprinklerNozzle34NeerShakti": { type: Number, default: 0 },
         "sprinklerNozzle34Mungipa": { type: Number, default: 0 },
         "stickStandRod": { type: Number, default: 0 },
         "tubeAssembly15Mtr": { type: Number, default: 0 },
         "ventury075Inches": { type: Number, default: 0 },
         "ventury263Mm": { type: Number, default: 0 },
         "75MmConnectorTail": { type: Number, default: 0 },
         "75MmConnectorCoupler": { type: Number, default: 0 },
      },
      totalItems: {
         type: Number,
         default: 0,
      },
      createdBy: {
         type: mongoose.Schema.Types.ObjectId,
         ref: "User",
         required: true,
      },
   },
   { timestamps: true }
);

inventorySchema.index({ farmerDealerCode: 1, financialYear: 1 });
inventorySchema.index({ date: -1 });
inventorySchema.index({ challanNo: 1 }, { unique: true });

const Inventory = mongoose.model("Inventory", inventorySchema);
export default Inventory;
